import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body>
        {children}
        <hr className="my-8"/>
      <footer>
        <audio controls>
          <source src="http://www.sousound.com/music/healing/healing_01.mp3" type="audio/mpeg" />
          Your browser does not support the audio element.
        </audio>
        <Link href="/contact">CONTACT</Link>
      </footer>
      </body>
    </html>
  );
}
